data:
  base_prior:
    _target_: src.distributions.gaussian.Gaussian
    mu: 2
    sigma: 4
  candidate_prior:
    _target_: src.distributions.laplace.Laplace
    mu: 0
    b: 1.376
#  candidate_prior:
#    _target_: src.distributions.cauchy.Cauchy
#    x0: 0
#    gamma: 0.954
  true_dgp:
    _target_: src.distributions.gaussian.Gaussian
    mu: 2
    sigma: 2
  loss:
    _target_: src.losses.gaussian_log_likelihood.GaussianLogLikelihood
    mu: 2
    sigma: 2
  loss_lr: 1
  observations_num: 1
  observations_path: data/laplace/observations.npy
  posterior_samples_path: data/laplace/posterior_samples.npy
  prior_samples_path: null
  posterior_samples_num: null
  prior_samples_num: null

model:
  _target_: src.bayesian_model.gaussian.SimpleGaussianModel

ksd:
  kernel:
    _target_: src.kernels.inverse_multiquadric.InverseUnivariateMultiquadricKernel
    lengthscale: null
    alpha: 0.5
    heuristic: True
  optimize:
    prior:
      Laplace:
          parameters_box_range:
            ranges:
              mu: [ 0.607, 0.607]
              b: [0.5, 2.5]
            nums:
              mu: 1
              b: 5

flags:
  plots:
    generate_plots:
      heatmap: True
      line_plot: True
      density_plot: True
      quadratic_form: True
    output_dir: outputs/paper/plots/univariate
playground:
  save_json: True
  save_csv: True
