data:
  base_prior:
    _target_: src.distributions.composite.CompositeProduct
    distributions:
      theta1:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 1
      theta2:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 1
  candidate_prior:
    _target_: src.distributions.composite.CompositeProduct
    distributions:
      theta1:
        _target_: src.distributions.gaussian.Gaussian
        mu: -5
        sigma: 4
      theta2:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 1
  true_dgp: null
  loss:
    _target_: src.losses.gaussian_log_likelihood.MultivariateGaussianLogLikelihood
    mu: [0, 0 ]
    cov: [ [ 1.0, 0.0 ], [ 0.0, 1.0 ] ]
  loss_lr: 1
  observations_path: data/comparison/two_gaussian/observations.npy
  posterior_samples_path: data/comparison/two_gaussian/posterior_samples.npy
  prior_samples_path: null
  observations_num: 1
  posterior_samples_num: null
  prior_samples_num: null

model:
  _target_: src.bayesian_model.gaussian.MultivariateGaussianModel

ksd:
  kernel:
    _target_: src.kernels.inverse_multiquadric.InverseMultivariateMultiquadricKernel
    lengthscale: null
    alpha: 0.5
    heuristic: True
  optimize:
    prior:
      Composite:
        combine_rule: product
        components:
          - name: theta1
            family: Gaussian
            parameters_box_range:
              ranges:
                mu: [ -15, 5 ]
                sigma: [ 3, 7 ]
              nums:
                mu: 41
                sigma: 5
          - name: theta2
            family: Gaussian
            parameters_box_range:
              ranges:
                mu: [ 0, 0 ]
                sigma: [ 1, 1 ]
              nums:
                mu: 1
                sigma: 1
flags:
  plots:
    generate_plots:
      heatmap: false
      line_plot: false
      density_plot: true
    output_dir: outputs/paper/plots/comparison/

playground:
  output_prefix: ark_param
  save_json: true
  save_csv: true