data:
  base_prior:
    _target_: src.distributions.gaussian.Gaussian
    mu: 2
    sigma: 4
  true_dgp:
    _target_: src.distributions.gaussian.Gaussian
    mu: 3
    sigma: 2
  loss:
    _target_: src.losses.gaussian_log_likelihood.GaussianLogLikelihood
    mu: 3
    sigma: 2
  loss_lr: 1
  observations_num: 500
  posterior_samples_num: 5000
  prior_samples_num: 5000

model:
  _target_: src.bayesian_model.gaussian.SimpleGaussianModel

ksd:
  kernel:
    _target_: src.kernels.inverse_multiquadric.InverseUnivariateMultiquadricKernel
    lengthscale: 1.0
    alpha: 0.5
    heuristic: False
  optimize:
    prior:
      Gaussian:
          parameters_box_range:
            ranges:
              mu: [ -10, 10]
              sigma: [2, 5]
            nums:
              mu: 21
              sigma: 4
      nonparametric:
        basis_funcs_type: SigmoidBasisFunction # PolynomialBasisFunction RBFBasisFunction SigmoidBasisFunction
        basis_funcs_kwargs: {"num_basis_functions": 5, "method": "kmeans", "scale": null, "scale_multiplier": 1.0} # {"degree": 3} for polynomial, {"num_basis_functions": 5, "method": "kmeans", "lengthscale": 5.0} for rbf, {"num_basis_functions": 5, "method": "kmeans", "scale": 5.0, "scale_multiplier": 1.0} for sigmoid
        radius_lower_bound: 2.0
        scale_samples: False

      LogNormal:
          parameters_box_range:
            ranges:
              mu_log: [ -10, 10]
              sigma_log: [2, 5]
            nums:
              mu_log: 21
              sigma_log: 4

    loss:
      GaussianLogLikelihood:
        parameters_box_range:
          ranges:
            lr: [0.05, 2.5]
          nums:
            lr: 15

flags:
  plots:
    generate_plots:
      heatmap: True
      line_plot: True
      density_plot: True
      quadratic_form: True
    output_dir: outputs/paper/plots/univariate
