data:
  base_prior:
    _target_: src.distributions.composite.CompositeProduct
    distributions:
      alpha:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta1:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta2:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta3:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta4:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta5:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      sigma:
        _target_: src.distributions.cauchy.HalfCauchy
        gamma: 2.5
  candidate_prior:
    _target_: src.distributions.composite.CompositeProduct
    distributions:
      alpha:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta1:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta2:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta3:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta4:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta5:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      sigma:
#        _target_: src.distributions.cauchy.HalfCauchy
#        gamma: 2.5
        _target_: src.distributions.log_normal.LogNormal
        mu_log: 1.0
        sigma_log: 1.5
#        _target_: src.distributions.gaussian.Gaussian
#        mu: 0
#        sigma: 3.5
  true_dgp: null
  loss:
    _target_: src.losses.gaussian_log_likelihood.GaussianARLogLikelihood
  loss_lr: 1
  observations_path: null # from posteriordb
  posterior_samples_path: null # from posteriordb
  prior_samples_path: null # from posteriordb
  observations_num: null
  posterior_samples_num: null
  prior_samples_num: null
  warmup: 0
  pdb_path: "/Users/arinaodv/Desktop/folder/study_phd/code/posteriordb/posterior_database"
  posterior_draws_corner_prior: "/Users/arinaodv/Desktop/folder/study_phd/code/posteriordb/posterior_database/reference_posteriors/draws/draws/arK-arK-corner.json"
  pdb_model_name: arK-arK

model:
  _target_: src.bayesian_model.posteriordb.ark.ArkBayesianModel

fd:
  kernel:
    _target_: src.kernels.inverse_multiquadric.InverseMultivariateMultiquadricKernel
    lengthscale: null
    alpha: 0.5
    heuristic: True
  optimize:
    prior:
      Composite:
        combine_rule: product
        components:
          - name: alpha
            family: Gaussian
            parameters_box_range:
              ranges:
                mu: [ -20, 20 ]
                sigma: [ 3.33, 30 ]
              nums:
                mu: 26
                sigma: 11
          - name: beta1
            family: Gaussian
            parameters_box_range:
              ranges:
                mu: [ -20, 20 ]
                sigma: [ 3.33, 30 ]
              nums:
                mu: 41
                sigma: 11
          - name: beta2
            family: Gaussian
            parameters_box_range:
              ranges:
                mu: [ -20, 20 ]
                sigma: [ 3.33, 30 ]
              nums:
                mu: 41
                sigma: 11
          - name: beta3
            family: Gaussian
            parameters_box_range:
              ranges:
                mu: [ -20, 20 ]
                sigma: [ 3.33, 30 ]
              nums:
                mu: 41
                sigma: 11
          - name: beta4
            family: Gaussian
            parameters_box_range:
              ranges:
                mu: [ -20, 20 ]
                sigma: [ 3.33, 30 ]
              nums:
                mu: 41
                sigma: 11
          - name: beta5
            family: Gaussian
            parameters_box_range:
              ranges:
                mu: [ -20, 20 ]
                sigma: [ 3.33, 30 ]
              nums:
                mu: 41
                sigma: 11
          - name: sigma
            family: Gamma
            parameters_box_range:
              ranges:
                alpha: [ 0.44, 4.0 ]
                theta: [ 0.06, 4.8 ]
              nums:
                alpha: 15
                theta: 26
#        eta_components:
#          - name: alpha
#            eta_range:
#              eta_1: [-18.75, 18.75]
#              eta_2: [-3.125, -0.5]
#          - name: beta1
#            eta_range:
#              eta_1: [-18.75, 18.75]
#              eta_2: [-3.125, -0.5]
#          - name: beta2
#            eta_range:
#              eta_1: [-18.75, 18.75]
#              eta_2: [-3.125, -0.5]
#          - name: beta3
#            eta_range:
#              eta_1: [-18.75, 18.75]
#              eta_2: [-3.125, -0.5]
#          - name: beta4
#            eta_range:
#              eta_1: [-18.75, 18.75]
#              eta_2: [-3.125, -0.5]
#          - name: beta5
#            eta_range:
#              eta_1: [-18.75, 18.75]
#              eta_2: [-3.125, -0.5]
#          - name: sigma
#            eta_range:
#              eta_1: [3.0, 10.11]
#              eta_2: [-22.22, -2.0]
        eta_components:
          - name: alpha
            eta_range:
              eta_1: [-55.56, 55.56]
              eta_2: [-5.56, -2.0]
          - name: beta1
            eta_range:
              eta_1: [-55.56, 55.56]
              eta_2: [-5.56, -2.0]
          - name: beta2
            eta_range:
              eta_1: [-55.56, 55.56]
              eta_2: [-5.56, -2.0]
          - name: beta3
            eta_range:
              eta_1: [-55.56, 55.56]
              eta_2: [-5.56, -2.0]
          - name: beta4
            eta_range:
              eta_1: [-55.56, 55.56]
              eta_2: [-5.56, -2.0]
          - name: beta5
            eta_range:
              eta_1: [-55.56, 55.56]
              eta_2: [-5.56, -2.0]
          - name: sigma
            eta_range:
              eta_1: [5.0, 10.11]
              eta_2: [-22.22, -5.0]

    loss:
      GaussianARLogLikelihood:
        parameters_box_range:
          ranges:
            lr: [ 0.05, 2.5 ]
          nums:
            lr: 21

flags:
  plots:
    generate_plots:
      heatmap: false
      line_plot: false
      density_plot: true
    output_dir: outputs/paper/plots/fisher/ark

playground:
  output_prefix: ark_param
  save_json: true
  save_csv: true
