data:
  base_prior:
    _target_: src.distributions.composite.CompositeProduct
    distributions:
      alpha:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta1:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta2:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta3:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta4:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta5:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      sigma:
        _target_: src.distributions.cauchy.HalfCauchy
        gamma: 2.5
  candidate_prior:
    _target_: src.distributions.composite.CompositeProduct
    distributions:
      alpha:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta1:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta2:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta3:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta4:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta5:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      sigma:
#        _target_: src.distributions.cauchy.HalfCauchy
#        gamma: 2.5
        _target_: src.distributions.log_normal.LogNormal
        mu_log: 1.0
        sigma_log: 1.5
#        _target_: src.distributions.gaussian.Gaussian
#        mu: 0
#        sigma: 3.5
  true_dgp: null
  loss:
    _target_: src.losses.gaussian_log_likelihood.GaussianARLogLikelihood
  loss_lr: 1
  observations_path: null # from posteriordb
  posterior_samples_path: null # from posteriordb
  prior_samples_path: null # from posteriordb
  observations_num: null
  posterior_samples_num: null
  prior_samples_num: null
  warmup: 0
  pdb_path: "/Users/arinaodv/Desktop/folder/study_phd/code/posteriordb/posterior_database"
  pdb_model_name: arK-arK

model:
  _target_: src.bayesian_model.posteriordb.ark.ArkBayesianModel

ksd:
  kernel:
    _target_: src.kernels.inverse_multiquadric.InverseMultivariateMultiquadricKernel
    lengthscale: null
    alpha: 0.5
    heuristic: True
  optimize:
    prior:
      Composite:
        combine_rule: product
        components:
          - name: alpha
            family: Gaussian
            parameters_box_range:
              ranges:
                mu: [ -5, 20 ]
                sigma: [ 4, 8 ]
              nums:
                mu: 26
                sigma: 5
          - name: beta1
            family: Gaussian
            parameters_box_range:
              ranges:
                mu: [ -20, 20 ]
                sigma: [ 3, 7 ]
              nums:
                mu: 41
                sigma: 5
          - name: beta2
            family: Gaussian
            parameters_box_range:
              ranges:
                mu: [ -20, 20 ]
                sigma: [ 3, 7 ]
              nums:
                mu: 41
                sigma: 5
          - name: beta3
            family: Gaussian
            parameters_box_range:
              ranges:
                mu: [ -20, 20 ]
                sigma: [ 3, 7 ]
              nums:
                mu: 41
                sigma: 5
          - name: beta4
            family: Gaussian
            parameters_box_range:
              ranges:
                mu: [ -20, 20 ]
                sigma: [ 3, 7 ]
              nums:
                mu: 41
                sigma: 5
          - name: beta5
            family: Gaussian
            parameters_box_range:
              ranges:
                mu: [ -20, 20 ]
                sigma: [ 3, 7 ]
              nums:
                mu: 41
                sigma: 5
          - name: sigma
            #            family: LogNormal
            #            parameters_box_range:
            #              ranges:
            #                mu_log: [ 1, 2]
            #                sigma_log: [ 1.0, 2.0 ]
            #              nums:
            #                mu_log: 11
            #                sigma_log: 11
            family: Gamma
            parameters_box_range:
              ranges:
                alpha: [ 1.1, 2.5 ]
                theta: [ 2.0, 4.5 ]
              nums:
                alpha: 15
                theta: 26

      nonparametric:
        basis_funcs_type: RBFBasisFunctionMultidim # PolynomialBasisFunctionMultidim # SigmoidBasisFunctionMultidim  # RBFBasisFunctionMultidim
        basis_funcs_kwargs: { "num_basis_functions": 15, "method": "kmeans", "lengthscale": null, "scale_multiplier": 1, "metric": "full" } # polynomial {"degree":3}  # sigmoid { "num_basis_functions": 15, "method": "farthest", "scale":null, "scale_multiplier": 1, "metric": "full" }   # for rbf { "num_basis_functions": 15, "method": "farthest", "lengthscale": null, "scale_multiplier": 1, "metric": "full" }
        radius_lower_bound: null
        scale_samples: False

    loss:
      GaussianARLogLikelihood:
        parameters_box_range:
          ranges:
            lr: [ 0.01, 2.5 ]
          nums:
            lr: 21

flags:
  plots:
    generate_plots:
      heatmap: false
      line_plot: false
      density_plot: true
    output_dir: outputs/paper/plots/fisher/ark

playground:
  output_prefix: ark_param
  save_json: true
  save_csv: true
