data:
  base_prior:
    _target_: src.distributions.composite.CompositeProduct
    distributions:
      gamma:
        _target_: src.distributions.cauchy.Cauchy
        x: 0
        gamma: 0.419
      delta:
        _target_: src.distributions.cauchy.Cauchy
        x: 0
        gamma: 1.099
  candidate_prior:
    _target_: src.distributions.composite.CompositeProduct
    distributions:
      gamma:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      delta:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
  true_dgp: null
  loss:
    _target_: src.losses.logistic_binomial_log_likelihood.ECMOBinomialLogLikelihood
  loss_lr: 1
  observations_path: /Users/arinaodv/Desktop/folder/study_phd/code/stein-sense/data/ecmo/observations.npy
  posterior_samples_path: /Users/arinaodv/Desktop/folder/study_phd/code/stein-sense/data/ecmo/posterior_samples.npy
  prior_samples_path: /Users/arinaodv/Desktop/folder/study_phd/code/stein-sense/data/ecmo/prior_samples.npy
  observations_num: null
  posterior_samples_num: null
  prior_samples_num: null

model:
  _target_: src.bayesian_model.ecmo.ecmo.ECMOModel

ksd:
  optimize:
    prior:
      nonparametric:
        basis_funcs_type: MaternBasisFunctionMultidim
        basis_funcs_kwargs: {"num_basis_functions": 10, "method": "quantile_grid", "scale_multiplier": 1, "metric":"full",
                             "estimation_centers_source":"posterior", "estimation_samples_source":"posterior"}
    loss:
      ECMOBinomialLogLikelihood:
        parameters_box_range:
          ranges:
            lr: [ 0.01, 2.5 ]
          nums:
            lr: 21

flags:
  plots:
    output_dir: outputs/paper/plots/comparison/ecmo

playground:
  output_prefix: ecmo
