data:
  base_prior:
    _target_: src.distributions.gaussian.Gaussian
    mu: 2
    sigma: 4
  true_dgp:
    _target_: src.distributions.gaussian.Gaussian
    mu: 3
    sigma: 2
  loss:
    _target_: src.losses.gaussian_log_likelihood.GaussianLogLikelihood
    mu: 3
    sigma: 2
  loss_lr: 1.0
  loss_lr_init: 1.0
  observations_num: 100
  observations_path: data/univariate_gaussian/observations.npy
  posterior_samples_path: data/univariate_gaussian/posterior_samples.npy
  prior_samples_path: data/univariate_gaussian/prior_samples.npy
  posterior_samples_num: 1000
  prior_samples_num: 1000

model:
  _target_: src.bayesian_model.gaussian.SimpleGaussianModel

optimize:
    nonparametric:
      basis_funcs_type: MaternBasisFunction
      basis_funcs_kwargs: {"num_basis_functions": 5, "method": "halton", "nu":2.0, "estimation_samples_source":"prior"}

flags:
  plots:
    output_dir: outputs/paper/plots/fisher/univariate/nonparam
