plot:
  font:
    size: 32  # match Overleaf 10pt font
    family: serif  # for LaTeX compatibility
    use_tex: true  # render text with LaTeX

  figure:
    size:
      width: 4  # in inches
      height: 3.2
    dpi: 300
    tight_layout: true

  color_palette:
    colors:
      - "#5A051A"  # cherry
#      - "#D20A2E"  # red
      - "#EE1E52"  # pink
      - "#F2BDCD"
#      - "#FF6B90"  # light-pink
      - "#1f77b4"  # blue
      - "#5b9bd5"  # lighter blue

  seaborn:
    style: "whitegrid"
    context: "paper"

  param_latex_names:
    mu: "$\\mu$"
    sigma: "$\\sigma$"
    mu_0: "$\\mu_0$"
    sigma_0: "$\\sigma_0$"
    alpha: "$\\alpha$"
    beta: "$\\beta$"
    prior: "$\\pi(\\mu_0)$"
    estimatedKSD: "$\\widehat{\\mathrm{KSD}}^2$"
    estimatedposterior: "$\\tilde{\\Pi}^m_\\text{ref}$"
    candidateposterior: "$\\tilde{\\Pi}$"
    estimatedKSDposteriors: "$\\widehat{\\mathrm{KSD}}^2(\\tilde{\\Pi}^m_\\text{ref}, \\tilde{\\Pi})$"

  y_axis:
    log_scale: false

  show_min_point: true
