data:
  base_prior:
    distribution:
    mu: 3
    sigma: 10
  true_dgp:
    distribution:
    mu: 3
    sigma: 2
  observations_num: 100
  posterior_samples_num: 1000


ksd:
  kernel:
    type:
    parameters:
      heuristic:
      lengthscale:
      variance:
      isotropic:
  optimize:
    prior:
      parameters_box_range:
        mu: [ -5, 5 ]
        sigma: [ 1, 7 ]

flags:
  plots:
    generate_plots:
      heatmap:
    save_plots: True
    output_dir:


