data:
  base_prior:
    _target_: src.distributions.composite.CompositeProduct
    distributions:
      alpha:
        _target_: src.distributions.cauchy.Cauchy
        x: 0
        gamma: 10
      beta:
        _target_: src.distributions.cauchy.Cauchy
        x: 0
        gamma: 2.5
  candidate_prior:
    _target_: src.distributions.composite.CompositeProduct
    distributions:
      alpha:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
      beta:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 10
  true_dgp: null
  loss:
    _target_: src.losses.logistic_binomial_log_likelihood.LogisticBinomialLogLikelihood
  loss_lr: 1
  observations_path: /Users/arinaodv/Desktop/folder/study_phd/code/stein-sense/data/bioassay/observations.npy
  posterior_samples_path: /Users/arinaodv/Desktop/folder/study_phd/code/stein-sense/data/bioassay/samples.npy
  prior_samples_path: null
  observations_num: null
  posterior_samples_num: null
  prior_samples_num: null

model:
  _target_: src.bayesian_model.bioassay.bioassay.BioassayModel

fd:
  kernel:
    _target_: src.kernels.inverse_multiquadric.InverseMultivariateMultiquadricKernel
    lengthscale: null
    alpha: 0.5
    heuristic: True
  optimize:
    prior:
      Composite:
        combine_rule: product
        components:
          - name: alpha
            family: Cauchy
            parameters_box_range:
              ranges:
                x: [ -3, 3 ]
                gamma: [ 0.7, 1.3 ]
              nums:
                mu: 1
                b: 12
          - name: beta
            family: Cauchy
            parameters_box_range:
              ranges:
                mu: [ -2, 2 ]
                b: [ -0.2, 14 ]
              nums:
                mu: 1
                b: 12
        eta_components:
          - name: alpha
            eta_range:
              eta_1: [ -0.12, 0.12 ]
              eta_2: [ -0.02, -0.00125 ]
          - name: beta
            eta_range:
              eta_1: [ -5.12, 5.12 ]
              eta_2: [ -1.28, -0.005 ]
    loss:
      LogisticBinomialLogLikelihood:
        parameters_box_range:
          ranges:
            lr: [ 0.01, 2.5 ]
          nums:
            lr: 21


flags:
  plots:
    output_dir: outputs/paper/plots/comparison/bioassay

playground:
  output_prefix: bioassay
