data:
  base_prior:
    _target_: src.distributions.composite.CompositeProduct
    distributions:
      alpha:
        _target_: src.distributions.gaussian.Gaussian
        mu: 9.31
        sigma: 100
      beta:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0
        sigma: 0.03
      sigma:
        _target_: src.distributions.uniform.Uniform
        low: 0
        high: inf
  candidate_prior:
    _target_: src.distributions.composite.CompositeProduct
    distributions:
      alpha:
        _target_: src.distributions.gaussian.Gaussian
        mu: 9.31
        sigma: 100
      beta:
        _target_: src.distributions.gaussian.Gaussian
        mu: 0.0
        sigma: 0.333
      sigma:
        _target_: src.distributions.log_normal.LogNormal
        mu_log: 0
        sigma_log: 1.0
  true_dgp: null
  loss:
    _target_: src.losses.gaussian_log_likelihood.GaussianLinearRegressionLogLikelihood
    scale: sigma
  loss_lr: 1
  observations_path: null # from posteriordb
  posterior_samples_path: null # from posteriordb
  prior_samples_path: null # from posteriordb
  observations_num: null
  posterior_samples_num: null
  prior_samples_num: null
  warmup: 0
  pdb_path: "/Users/arinaodv/Desktop/folder/study_phd/code/posteriordb/posterior_database"
  pdb_model_name: kilpisjarvi_mod-kilpisjarvi

model:
  _target_: src.bayesian_model.posteriordb.kilpisjarvi.KilpisjarviBayesianModel

ksd:
  kernel:
    _target_: src.kernels.inverse_multiquadric.InverseMultivariateMultiquadricKernel
    lengthscale: null
    alpha: 0.5
    heuristic: True

flags:
  plots:
    generate_plots:
      heatmap: false
      line_plot: false
      density_plot: true
    output_dir: outputs/paper/plots/kilpisjarvi

playground:
  output_prefix: kilpisjarvi_param
  save_json: true
  save_csv: true
